### ISSUE TITLE
Try and avoid `-URL` when you can do `URL`

### ISSUE THREAD

**Issue by joker314** [scratchlyurl/go#5]
If #3 is done then this will be fixed, but if there is no matching `type` then it should simply replace `scratch.us.to` with `scratch.mit.edu`

**Comment by WorldLanguages** [comment]
What about a direct link starting with s? It would think it's a studio, right?

**Comment by joker314** [comment]
Hmm, I dunno. I think that
`https://scratch.mit.edu/help` should just be `scratch.us.to/help` but `/potato` could be confused with a project, so it should be `/-potato` if you see what I mean?

**Comment by WorldLanguages** [comment]
Yes, I get it :) I agree

**Comment by WorldLanguages** [comment]
Even I don't think this would be necessary

**Comment by WorldLanguages** [comment]
oops accidentally closed
