### ISSUE TITLE
Encoder?

### ISSUE THREAD

**Issue by joker314** [scratchlyurl/go#6]
I am working on one already, but I think there should be an encoder that takes a URL like `scratch.mit.edu/discuss` and gives as its output `scratch.us.to/d` or whatever the correct URL is.

**Comment by WorldLanguages** [comment]
Yes, we need an encoder

**Comment by WorldLanguages** [comment]
https://github.com/scratchlyurl/shortener

**Comment by joker314** [comment]
Ok.
