### ISSUE TITLE
Scratch Promoting and Base 36 encoding

### ISSUE THREAD

**Issue by ghost** [scratchlyurl/go#9]
Are you going to make a project advertising the linking? If so maybe have the project do all the work for the scratcher. So the project would choose the domain link that is the shortest, show a variety of categories (eg. Forums, Projects, Scratchers, Studios and Other) where the scratcher using the project gets to choose which one they'll use. Then each category will come up with it's own sub-categories and the Scratcher chooses one of these. Then it will ask for the additional information (still telling the scratcher what it is possible to do with it) and develop the link (if the sub-category uses Base 36 encoding the project will encode the information.

**Comment by WorldLanguages** [comment]
If someone helps we will make a shortener: https://github.com/scratchlyurl/shortener

**Comment by ghost** [comment]
what do you mean? What needs to be done? I may be able to help.

**Comment by WorldLanguages** [comment]
:) jsfiddle? https://jsfiddle.net/vuta1rx7/3/#&togetherjs=8O7ga4uUf6
